var num1 = 20;
var num2 = 3;
var add = num1 + num2;
var sub = num1 - num2;
var mul = num1 * num2;
var div = num1 / num2;
var mod = num1 % num2;
console.log("Sum is: " + add);
console.log("Difference is: " + sub);
console.log("Product is: " + mul);
console.log("Division is: " + div);
console.log("Mosulo Division is: " + mod);
